stages:
    - name: Test
      steps:
          - runScriptConfig:
                image: node:slim
                shellScript: NODE_ENV=development yarn && NODE_ENV=development yarn test:ci
            when:
                branch:
                    include:
                        - staging
                        - prod
                event:
                    include:
                        - push
    - name: Build
      steps:
          - publishImageConfig:
                dockerfilePath: ./Dockerfile
                buildContext: .
                # You need to modify this line here and into deployment.yml
                tag: aDockerUser/aDockerRepo:${CICD_GIT_COMMIT}
                pushRemote: true
                registry: index.docker.io
      when:
          branch:
              include:
                  - staging
                  - prod
          event:
              include:
                  - push
    - name: Deploy
      steps:
          - applyYamlConfig:
                path: ./deployment.yml
branch:
    include:
        - staging
        - prod
notification: {}
